sudo: false

os:
  - linux

compiler:
  - gcc

language:
  - c

services:
  - docker

before_install:
  - docker pull ebassi/emeusci

before_script:
  - echo FROM ebassi/emeusci > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t emeusci:withgit .

script:
  - docker run withgit /bin/sh -c "cd /root && TRAVIS=1 CC=$CC ./emeus-run-tests.sh"
